# Generated by Django 5.0.6 on 2024-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemption',
            name='available_exemptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exemption',
            name='exemptions_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exemption',
            name='identifier',
            field=models.IntegerField(),
        ),
    ]
