# Generated by Django 5.0.6 on 2024-07-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptions', '0002_exemption_available_exemptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('classes', models.ManyToManyField(blank=True, related_name='classes', to='exemptions.stringslist')),
                ('exempted_ids', models.ManyToManyField(blank=True, related_name='exempted_students', to='exemptions.stringslist')),
            ],
        ),
    ]
