# Generated by Django 5.0.6 on 2024-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptions', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='exemptions.courselist'),
        ),
    ]
