# Generated by Django 5.0.6 on 2024-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptions', '0004_courselist_alter_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemption',
            name='exempted_strings',
            field=models.ManyToManyField(blank=True, related_name='exempted_models', to='exemptions.courselist'),
        ),
    ]
