# Generated by Django 5.0.6 on 2024-08-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptions', '0005_alter_exemption_exempted_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemption',
            name='identifier',
            field=models.CharField(max_length=6),
        ),
    ]
